CREATE TABLE staging_outfield_players (
    team_name VARCHAR(100),
    date DATE,
    match VARCHAR(100),
    competition VARCHAR(100),
    player VARCHAR(100),
    periode VARCHAR(50),
    segment VARCHAR(50),

    attack_buts INT,
    attack_centres_precis INT,
    attack_centres_total INT,
    attack_courses_progressives INT,
    attack_dribbles_reussis INT,
    attack_dribbles_total INT,
    attack_duels_offensifs_gagnes INT,
    attack_duels_offensifs_total INT,
    attack_fautes_subies INT,
    attack_hors_jeu INT,
    attack_passes_decisives INT,
    attack_passes_decisives_tir INT,
    attack_tirs_cadres INT,
    attack_tirs_total INT,
    attack_touches_surface_reparation INT,
    attack_xg FLOAT,

    defense_cartons_jaunes INT,
    defense_cartons_rouges INT,
    defense_degagements_total INT,
    defense_duels_aeriens_gagnes INT,
    defense_duels_aeriens_total INT,
    defense_duels_defensifs_gagnes INT,
    defense_duels_defensifs_total INT,
    defense_duels_perdus_gagnes INT,
    defense_duels_perdus_total INT,
    defense_fautes_total INT,
    defense_interceptions_total INT
);
